- name: "Install the 'xdm' application package"
  ansible.builtin.package:
    name: xdm
    state: present
  become: true
  become_user: root

- name: "Install supporting 'x11-apps' package (for xclock)"
  ansible.builtin.package:
    name: x11-apps
    state: present
  become: true
  become_user: root

