- name: "Check if user-selected 'session' var is supported"
  ansible.builtin.include_tasks: check_session_name/main.yml

- name: "Install XDM application"
  ansible.builtin.include_tasks: install_xdm/main.yml

- name: "Configure startup of desktop session"
  ansible.builtin.include_tasks: config_desktop_session/main.yml

