- name: "Run all role tasks for Linux"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    system_xdm_xresources_file_path: "{{ linux_xdm_xresources_file_path }}"
    system_xdm_xsetup_file_path: "{{ linux_xdm_xsetup_file_path }}"
  when: ansible_system == "Linux"

- name: "Run all role tasks for FreeBSD"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    system_xresources_file_path: "{{ freebsd_xdm_xresources_file_path }}"
    system_xdm_xsetup_file_path: "{{ freebsd_xdm_xsetup_file_path }}"
  when: ansible_os_family == "FreeBSD"

