- name: "Run all role tasks for Linux"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    system_xdm_xresources_file_path: "{{ xdm_linux_xdm_xresources_file_path }}"
    system_xdm_xsetup_file_path: "{{ xdm_linux_xdm_xsetup_file_path }}"
    system_xdm_buttons_file_path: "{{ xdm_linux_xdm_buttons_file_path }}"
    system_xdm_post_login_file_path: "{{ xdm_linux_xdm_post_login_file_path }}"
    system_shutdown_cmd: "{{ xdm_linux_shutdown_cmd }}"
    system_restart_cmd: "{{ xdm_linux_restart_cmd }}"
    system_virt_consoles_msg: "{{ xdm_linux_virt_consoles_msg }}"
  when: ansible_system == "Linux"

- name: "Run all role tasks for FreeBSD"
  ansible.builtin.include_tasks: run_all_tasks.yml
  vars:
    system_xresources_file_path: "{{ xdm_freebsd_xdm_xresources_file_path }}"
    system_xdm_xsetup_file_path: "{{ xdm_freebsd_xdm_xsetup_file_path }}"
    system_xdm_buttons_file_path: "{{ xdm_freebsd_xdm_buttons_file_path }}"
    system_xdm_post_login_file_path: "{{ xdm_freebsd_xdm_post_login_file_path }}"
    system_shutdown_cmd: "{{ xdm_freebsd_shutdown_cmd }}"
    system_restart_cmd: "{{ xdm_freebsd_restart_cmd }}"
    system_virt_consoles_msg: "{{ xdm_freebsd_virt_consoles_msg }}"
  when: ansible_os_family == "FreeBSD"

