- name: "Remove and unconfigure any other DMs that may be installed"
  ansible.builtin.include_tasks: remove_other_dms/main.yml
  when: remove_other_display_managers

- name: "Check if user-selected 'session' var is supported"
  ansible.builtin.include_tasks: check_session_name/main.yml

- name: "Install XDM application"
  ansible.builtin.include_tasks: install/main.yml

- name: "Configure startup of desktop session"
  ansible.builtin.include_tasks: configure/main.yml

