- name: "Install the 'xorg-xdm' application package"
  ansible.builtin.package:
    name: xorg-xdm
    state: present
  become: true
  become_user: root

- name: "Install supporting 'xcursor-themes' package"
  ansible.builtin.package:
    name: xcursor-themes
    state: present
  become: true
  become_user: root

