- name: "Install the 'xorg-xdm' application package"
  ansible.builtin.package:
    name: xorg-xdm
    state: present
  become: true
  become_user: root

- name: "Install supporting 'xorg-xsetroot' package"
  ansible.builtin.package:
    name: xorg-xsetroot
    state: present
  become: true
  become_user: root

- name: "Install supporting 'xorg-xclock' package"
  ansible.builtin.package:
    name: xorg-xclock
    state: present
  become: true
  become_user: root

- name: "Install supporting 'xorg-xmessage' package (for showing buttons)"
  ansible.builtin.package:
    name: xorg-xmessage
    state: present
  become: true
  become_user: root

- name: "Install supporting 'xkill', 'xwininfo' packages (for stopping login screen apps)"
  ansible.builtin.package:
    name:
      - xorg-xkill
      - xorg-xwininfo
    state: present
  become: true
  become_user: root

