- name: "Install the 'xdm' application package"
  ansible.builtin.package:
    name: xdm
    state: present
  become: true
  become_user: root

- name: "Install supporting 'xsetroot' package"
  ansible.builtin.package:
    name: xsetroot
    state: present
  become: true
  become_user: root

- name: "Install supporting 'xclock' package"
  ansible.builtin.package:
    name: xclock
    state: present
  become: true
  become_user: root

- name: "Install supporting 'xmessage' package (for showing buttons)"
  ansible.builtin.package:
    name: xmessage
    state: present
  become: true
  become_user: root

- name: "Install supporting 'xkill', 'xwininfo' packages (for stopping login screen apps)"
  ansible.builtin.package:
    name:
      - xkill
      - xwininfo
    state: present
  become: true
  become_user: root

