- name: "Install the 'xdm' application package"
  ansible.builtin.package:
    name: xdm
    state: present
  become: true
  become_user: root

- name: "Install supporting 'xclock' package"
  ansible.builtin.package:
    name: xclock
    state: present
  become: true
  become_user: root

