- name: "Remove terminal configuration for Ly in '{{ freebsd_terminal_config_path }}'"
  ansible.builtin.blockinfile:
    path: "{{ freebsd_terminal_config_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Ly display manager terminal config"
    state: absent
  become: true
  become_user: root

- name: "Restore default virtual console {{ freebsd_ly_virtual_console_num }} config in '{{ freebsd_console_config_path }}'"
  ansible.builtin.lineinfile:
    path: "{{ freebsd_console_config_path }}"
    regexp: >-
      ^(# )?ttyv{{ freebsd_ly_virtual_console_num }}(.*)$
    line: >-
      ttyv{{ freebsd_ly_virtual_console_num }}\2
    state: present
    firstmatch: true
    backrefs: true
    backup: true
  become: true
  become_user: root

- name: "Remove virtual console {{ freebsd_ly_virtual_console_num }} config for Ly in '{{ freebsd_console_config_path }}'"
  ansible.builtin.blockinfile:
    path: "{{ freebsd_console_config_path }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Ly virtual console config"
    state: absent
  become: true
  become_user: root

