- name: "Configure '{{ session }}' desktop session for user '{{ xdm_user_name }}'"
  ansible.builtin.template:
    dest: "/home/{{ xdm_user_name }}/.xsession"
    src: "{{ session }}.j2"
    owner: "{{ xdm_user_name }}"
    group: "{{ xdm_user_name }}"
    mode: '700'
    force: yes
  become: true
  become_user: root

- name: "Enable xdm display manager to start at boot"
  ansible.builtin.service:
    name: xdm-archlinux
    enabled: yes
  become: true
  become_user: root
  when: ansible_os_family == "Archlinux"

- name: "Enable xdm display manager to start at boot"
  ansible.builtin.service:
    name: xdm
    enabled: yes
  become: true
  become_user: root
  when: ansible_os_family == "FreeBSD"

