- name: "Configure XDM service"
  ansible.builtin.include_tasks: service.yml

- name: "Configure XDM login screen"
  ansible.builtin.include_tasks: login_screen.yml

- name: "Configure XDM post-login actions"
  ansible.builtin.include_tasks: post_login.yml

