- name: "Stop all login screen apps (started by Xsetup) in {{ system_xdm_xstartup_file_path }}"
  ansible.builtin.blockinfile:
    path: "{{ system_xdm_xstartup_file_path }}"
    insertafter: >-
      ^#!/bin/sh$
    block: "xwininfo -root -children | grep '  0x' | cut -d' ' -f6 | xargs -n1 xkill -id"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: Stop All Login Screen Apps"
    create: no
    state: present
  become: true
  become_user: root

